import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="content w-full text-center">
      <Head>
        <title>DataPortfolio API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span className="text-white">Something awesome is coming!</span>
    </div>
  )
}
